/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/WawaOffice.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/WawaOffice-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.chair.geometry} material={materials.chair} position={[0.56, 0.07, 0.55]} rotation={[-Math.PI, 1.26, -Math.PI]} scale={[0.16, 0.16, 0.13]} />
      <mesh geometry={nodes.photo.geometry} material={materials.photoGraph} position={[-0.91, 1.29, 0.39]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.13, 0.17, 0.02]} />
      <mesh geometry={nodes.blanket.geometry} material={materials.rugBlanket} position={[-0.57, 0.35, 0.25]} rotation={[Math.PI, -1.49, Math.PI]} scale={0.48} />
      <mesh geometry={nodes.matress.geometry} material={materials.matress} position={[-0.59, 0.31, 0.4]} rotation={[0, -1.57, 0]} scale={[-0.52, -0.07, -0.32]} />
      <mesh geometry={nodes.bedroomCube.geometry} material={materials.bedroomCube} position={[-0.11, 0.81, 0.18]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.painting.geometry} material={materials.sidePainting} position={[-0.09, 0.38, 0.87]} rotation={[-2.79, -0.12, 1.62]} scale={[0.03, 0.13, 0.02]} />
      <mesh geometry={nodes.deskText.geometry} material={materials.deskMessage} position={[0.53, 0.36, 0.72]} rotation={[Math.PI / 2, -1.57, 0]} scale={[0.03, 0.04, 0.03]} />
      <mesh geometry={nodes.sirmurSign.geometry} material={materials.sirmurNeon} position={[0.05, 1.21, 0.9]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.02, 0.03, 0.03]} />
      <mesh geometry={nodes.textSkills.geometry} material={materials.batSkills} position={[-0.87, 0.65, 0.08]} rotation={[1.85, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.bballHoop.geometry} material={materials.bballHoopTex} position={[-0.72, 1.19, -0.53]} rotation={[0, Math.PI / 2, 0]} scale={[0.19, 0.23, 0.02]} />
      <mesh geometry={nodes.bedFrame.geometry} material={materials.bedFrame} position={[-0.59, 0.19, 0.5]} rotation={[0, Math.PI / 2, 0]} scale={[0.01, 0.05, 0.01]} />
      <mesh geometry={nodes.monitor.geometry} material={materials.monitorPortrait} position={[0.56, 0.41, 0.84]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.05, 0.01]} />
      <mesh geometry={nodes.cielingpart.geometry} material={materials.woodBeamz} position={[0.03, 1.82, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.39, 0.16, 0.05]} />
      <mesh geometry={nodes.XMASlights.geometry} material={materials.xmasLightz} position={[0.03, 1.82, 0.01]} rotation={[0, 1.57, 0]} scale={0.18} />
      <mesh geometry={nodes.neonSkills.geometry} material={materials.neonSkills} position={[-0.93, 0.37, -0.56]} rotation={[0, Math.PI / 2, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.lavaNeon.geometry} material={materials.neonSkillsWall} position={[-0.93, 0.94, -0.48]} rotation={[0, Math.PI / 2, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.teddybear.geometry} material={materials.teddybear} position={[-0.68, 0.48, 0.53]} rotation={[-Math.PI, 0.32, -Math.PI]} scale={0.04} />
      <mesh geometry={nodes.Desk.geometry} material={materials.desk} position={[0.88, 0.46, 0.65]} rotation={[0, Math.PI / 2, 0]} scale={[0.01, 0.05, 0.01]} />
      <mesh geometry={nodes.nightstand.geometry} material={materials.nightStand} position={[-0.09, 0.1, 0.88]} rotation={[0, Math.PI / 2, 0]} scale={[0.01, 0.05, 0.01]} />
      <mesh geometry={nodes.pillow.geometry} material={materials.lamp} position={[-0.59, 0.47, 0.8]} rotation={[-0.7, -1.57, 0]} scale={[0.13, 0.13, 0.2]} />
      <mesh geometry={nodes.rug.geometry} material={materials.blackRug} position={[0.36, -0.01, -0.31]} rotation={[Math.PI, -1.49, Math.PI]} scale={0.48} />
      <mesh geometry={nodes.mouseKeyboard.geometry} material={materials.keyboardMouse} position={[0.53, 0.27, 0.59]} rotation={[Math.PI / 2, -1.57, 0]} scale={[0.03, 0.04, 0.03]} />
      <mesh geometry={nodes.lavaNeon001.geometry} material={materials.lavaLamp} position={[-0.83, 0.91, -0.39]} rotation={[0, Math.PI / 2, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Text008.geometry} material={materials.backSIGN} position={[-0.08, 1.3, 1.15]} rotation={[Math.PI / 2, 0, 0]} scale={[0.44, 0.35, 0.44]} />
      <mesh geometry={nodes.Text015.geometry} material={materials.emailText} position={[0.08, 0.42, 1.16]} rotation={[Math.PI / 2, 0, 0]} scale={[0.34, 0.1, 0.34]} />
      <mesh geometry={nodes.Icosphere001.geometry} material={materials['Material.007']} position={[0.32, 0.35, -0.36]} rotation={[0, Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.chalk00.geometry} material={materials.poolChalk} position={[0.47, 0.37, 0.11]} rotation={[0, 1.46, 0]} scale={0.01} />
      <mesh geometry={nodes.poolTableFinished.geometry} material={materials.poolTable} position={[0.36, 0.26, -0.32]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.04, 0.15, 0.02]} />
      <mesh geometry={nodes.poolCue00.geometry} material={materials.poolCue} position={[0.08, 0.43, -0.74]} rotation={[2.95, 0.44, -1.09]} scale={[0.33, 0, 0]} />
      <mesh geometry={nodes.wallMount00004.geometry} material={materials.poolLamp} position={[0.4, 1.4, -0.33]} scale={[0.03, 0.11, 0.01]} />
      <mesh geometry={nodes.photo001.geometry} material={materials.selfPortrait} position={[-1.09, 0.97, 0.46]} rotation={[Math.PI / 2, -1.55, -Math.PI]} scale={[0.36, 0.47, 0.02]} />
      <mesh geometry={nodes.photo002.geometry} material={materials.backPhoto00} position={[-1.09, 1.34, -0.55]} rotation={[Math.PI / 2, -1.55, -Math.PI]} scale={[0.17, 0.29, 0.02]} />
      <mesh geometry={nodes.photo003.geometry} material={materials.backPhoto01} position={[-1.08, 0.6, -0.55]} rotation={[Math.PI / 2, -1.55, -Math.PI]} scale={[0.17, 0.29, 0.02]} />
    </group>
  )
}

useGLTF.preload('/WawaOffice-transformed.glb')
