/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/WawaOffice.glb
*/
import { useGLTF, useScroll } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { gsap } from 'gsap';
import React, { useLayoutEffect, useRef } from 'react';

export const FLOOR_HEIGHT = 0;
export const NB_FLOORS = 4;

export function Office(props) {
  const { nodes, materials } = useGLTF('./models/WawaOffice-transformed.glb')
  const ref = useRef();
  const tl = useRef();
  const libraryRef = useRef();
  const atticRef = useRef();
  const bootyRef = useRef();
  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    //VERTICAL ANIMATION
    tl.current.to(
        ref.current.position,
        {
            duration: 3,
            
        },
        0
    );
    //Office Rotation
    tl.current.to(
      ref.current.rotation,
      { duration: 1, x: 0, y: -Math.PI / 1.3, z: 0},
      0
    );
    tl.current.to(
      ref.current.rotation,
      { duration: 1, x: 0, y: Math.PI / 2, z: 0},
      1
    );
    tl.current.to(
      ref.current.rotation,
      { duration: 1, x: 0, y: -Math.PI / 1.6, z: 0},
      2
    );
   //Office Movement
   tl.current.to(
     ref.current.position,
     { duration: 1, x: -2, z: -2, y: -2},
     0
   );
   tl.current.to(
    ref.current.position,
    { duration: 1, x: 1, z: 1, y:0},
    1
  );
  tl.current.to(
    ref.current.position,
    { duration: 1, x: 0, z: 0, y:-1},
    2
  );
    
   
  }, []);


  return (
    <group {...props} dispose={null} ref={ref}
    position={[0, -1, 0]} rotation={[ 0.8, -1.25, Math.PI / 3]} > 
        <mesh geometry={nodes.chair.geometry} material={materials.chair} position={[0.56, 0.07, 0.52]} rotation={[-Math.PI, 1.26, -Math.PI]} scale={[0.16, 0.16, 0.13]} />
      <mesh geometry={nodes.photo.geometry} material={materials.photoGraph} position={[-0.91, 1.29, 0.35]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.13, 0.17, 0.02]} />
      <mesh geometry={nodes.blanket.geometry} material={materials.rugBlanket} position={[-0.57, 0.35, 0.21]} rotation={[Math.PI, -1.49, Math.PI]} scale={0.48} />
      <mesh geometry={nodes.matress.geometry} material={materials.matress} position={[-0.59, 0.31, 0.36]} rotation={[0, -1.57, 0]} scale={[-0.52, -0.07, -0.32]} />
      <mesh geometry={nodes.bedroomCube.geometry} material={materials.bedroomCube} position={[-0.11, 0.81, 0.14]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.painting.geometry} material={materials.sidePainting} position={[-0.11, 0.36, 0.84]} rotation={[-2.79, -0.12, 1.62]} scale={[0.03, 0.13, 0.02]} />
      <mesh geometry={nodes.deskText.geometry} material={materials.deskMessage} position={[0.53, 0.331, 0.68]} rotation={[Math.PI / 2, -1.57, 0]} scale={[0.03, 0.04, 0.03]} />
      <mesh geometry={nodes.sirmurSign.geometry} material={materials.sirmurNeon} position={[0.05, 1.21, 0.87]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.023, 0.023, 0.023]} />
      <mesh geometry={nodes.textSkills.geometry} material={materials.batSkills} position={[-0.86, 0.64, 0.06]} rotation={[1.95, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.bballHoop.geometry} material={materials.bballHoopTex} position={[-0.72, 1.19, -0.57]} rotation={[0, Math.PI / 2, 0]} scale={[0.19, 0.23, 0.02]} />
      <mesh geometry={nodes.bedFrame.geometry} material={materials.bedFrame} position={[-0.59, 0.19, 0.46]} rotation={[0, Math.PI / 2, 0]} scale={[0.0055, 0.055, 0.0055]} />
      <mesh geometry={nodes.monitor.geometry} material={materials.monitorPortrait} position={[0.56, 0.41, 0.8]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.05, 0.01]} />
      <mesh geometry={nodes.cielingpart.geometry} material={materials.woodBeamz} position={[0.03, 1.82, -0.03]} rotation={[0, -Math.PI / 2, 0]} scale={[0.39, 0.16, 0.05]} />
      <mesh geometry={nodes.XMASlights.geometry} material={materials.xmasLightz} position={[0.03, 1.82, -0.03]} rotation={[0, 1.57, 0]} scale={[0.18, 0.18, 0.193]} />
      <mesh geometry={nodes.neonSkills.geometry} material={materials.neonSkills} position={[-0.93, 0.32, -0.6]} rotation={[0, Math.PI / 2, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.lavaNeon.geometry} material={materials.neonSkillsWall} position={[-0.929, 0.94, -0.52]} rotation={[0, Math.PI / 2, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.teddybear.geometry} material={materials.teddybear} position={[-0.68, 0.48, 0.49]} rotation={[-Math.PI, 0.32, -Math.PI]} scale={0.04} />
      <mesh geometry={nodes.Desk.geometry} material={materials.desk} position={[0.88, 0.42, 0.61]} rotation={[0, Math.PI / 2, 0]} scale={[0.0055, 0.05, 0.0055]} />
      <mesh geometry={nodes.nightstand.geometry} material={materials.nightStand} position={[-0.1, 0.1, 0.84]} rotation={[0, Math.PI / 2, 0]} scale={[0.005, 0.05, 0.006]} />
      <mesh geometry={nodes.pillow.geometry} material={materials.lamp} position={[-0.59, 0.47, 0.76]} rotation={[-0.7, -1.57, 0]} scale={[0.13, 0.13, 0.2]} />
      <mesh geometry={nodes.rug.geometry} material={materials.blackRug} position={[0.36, -0.01, -0.35]} rotation={[Math.PI, -1.49, Math.PI]} scale={0.48} />
      <mesh geometry={nodes.mouseKeyboard.geometry} material={materials.keyboardMouse} position={[0.53, 0.248, 0.56]} rotation={[Math.PI / 2, -1.57, 0]} scale={[0.03, 0.04, 0.03]} />
      <mesh geometry={nodes.lavaNeon001.geometry} material={materials.lavaLamp} position={[-0.83, 0.93, -0.43]} rotation={[0, Math.PI / 2, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Text008.geometry} material={materials.backSIGN} position={[-0.08, 1.3, 1.12]} rotation={[Math.PI / 2, 0, 0]} scale={[0.44, 0.35, 0.44]} />
      <mesh geometry={nodes.Text015.geometry} material={materials.emailText} position={[0.08, 0.42, 1.12]} rotation={[Math.PI / 2, 0, 0]} scale={[0.34, 0.1, 0.34]} />
      <mesh geometry={nodes.Icosphere001.geometry} material={materials['Material.007']} position={[0.32, 0.35, -0.4]} rotation={[0, Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.chalk00.geometry} material={materials.poolChalk} position={[0.47, 0.37, 0]} rotation={[0, 1.46, 0]} scale={[0.006, 0.006, 0.006]} />
      <mesh geometry={nodes.poolTableFinished.geometry} material={materials.poolTable} position={[0.36, 0.26, -0.36]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.04, 0.15, 0.02]} />
      <mesh geometry={nodes.poolCue00.geometry} material={materials.poolCue} position={[0.08, 0.43, -0.77]} rotation={[2.95, 0.44, -1.09]} scale={[0.33, 0, 0]} />
      <mesh geometry={nodes.wallMount00004.geometry} material={materials.poolLamp} position={[0.43, 1.42, -0.37]} scale={[0.03, 0.11, 0.01]} />
      <mesh geometry={nodes.photo001.geometry} material={materials.selfPortrait} position={[-1.09, 0.97, 0.46]} rotation={[Math.PI / 2, -1.55, -Math.PI]} scale={[0.36, 0.47, 0.02]} />
      <mesh geometry={nodes.photo002.geometry} material={materials.backPhoto00} position={[-1.09, 1.34, -0.55]} rotation={[Math.PI / 2, -1.55, -Math.PI]} scale={[0.17, 0.29, 0.02]} />
      <mesh geometry={nodes.photo003.geometry} material={materials.backPhoto01} position={[-1.08, 0.6, -0.55]} rotation={[Math.PI / 2, -1.55, -Math.PI]} scale={[0.17, 0.29, 0.02]} />
      
      <group position={[0, 0.11, -0.23]}>
        <group ref={libraryRef}>
        
        </group>
      </group>
      <group position={[-1.97, 4.23, -2.2]}>
        <group ref={atticRef}>
        
        </group>
      </group>
      <group position={[0, -1, 0]}>
        <group ref={bootyRef}>
      
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('./models/WawaOffice-transformed.glb')


{/* <mesh name="chair" geometry={nodes.chair.geometry} material={materials.chair} position={[0.56, 0.07, 0.4]} rotation={[-Math.PI, 1.26, -Math.PI]} scale={[0.16, 0.16, 0.13]} />
        <mesh name="photo" geometry={nodes.photo.geometry} material={materials.photoGraph} position={[-0.91, 1.29, 0.35]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.13, 0.17, 0.02]} />
        <mesh name="blanket" geometry={nodes.blanket.geometry} material={materials.rugBlanket} position={[-0.57, 0.35, 0.21]} rotation={[Math.PI, -1.49, Math.PI]} scale={0.48} />
        <mesh name="matress" geometry={nodes.matress.geometry} material={materials.matress} position={[-0.59, 0.31, 0.36]} rotation={[0, -1.57, 0]} scale={[-0.52, -0.07, -0.32]} />
        <mesh name="bedroomCube" geometry={nodes.bedroomCube.geometry} material={materials.bedroomCube} position={[-0.11, 0.81, 0.14]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="painting" geometry={nodes.painting.geometry} material={materials.sidePainting} position={[-0.11, 0.38, 0.84]} rotation={[-2.79, -0.12, 1.62]} scale={[0.03, 0.13, 0.02]} />
        <mesh name="deskText" geometry={nodes.deskText.geometry} material={materials.deskMessage} position={[0.46, 0.36, 0.68]} rotation={[Math.PI / 2, -1.57, 0]} scale={[0.03, 0.04, 0.03]} />
        <mesh name="sirmurSign" geometry={nodes.sirmurSign.geometry} material={materials.sirmurNeon} position={[0.05, 1.19, 0.87]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.023, 0.023, 0.023]} />
        <mesh name="textSkills" geometry={nodes.textSkills.geometry} material={materials.batSkills} position={[-0.87, 0.65, 0.04]} rotation={[1.85, 0, -Math.PI / 2]} scale={0.32} />
        <mesh name="bballHoop" geometry={nodes.bballHoop.geometry} material={materials.bballHoopTex} position={[-0.72, 1.19, -0.57]} rotation={[0, Math.PI / 2, 0]} scale={[0.19, 0.23, 0.02]} />
        <mesh name="bedFrame" geometry={nodes.bedFrame.geometry} material={materials.bedFrame} position={[-0.59, 0.19, 0.46]} rotation={[0, Math.PI / 2, 0]} scale={[0.0055, 0.055, 0.0055]}  />
        <mesh name="monitor" geometry={nodes.monitor.geometry} material={materials.monitorPortrait} position={[0.56, 0.41, 0.8]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.05, 0.01]} />
        <mesh name="cielingpart" geometry={nodes.cielingpart.geometry} material={materials.woodBeamz} position={[0.03, 1.82, -0.03]} rotation={[0, -Math.PI / 2, 0]} scale={[0.39, 0.16, 0.05]} />
        <mesh name="XMASlights" geometry={nodes.XMASlights.geometry} material={materials.xmasLightz} position={[0.03, 1.82, -0.03]} rotation={[0, 1.57, 0]} scale={[0.18, 0.18, 0.193]} />
        <mesh name="neonSkills" geometry={nodes.neonSkills.geometry} material={materials.neonSkills} position={[-0.94, 0.37, -0.6]} rotation={[0, Math.PI / 2, 0]} scale={[0.03, 0.01, 0.03]} />
        <mesh name="lavaNeon" geometry={nodes.lavaNeon.geometry} material={materials.neonSkillsWall} position={[-0.93, 0.94, -0.52]} rotation={[0, Math.PI / 2, 0]} scale={[0.03, 0.01, 0.03]} />
        <mesh name="teddybear" geometry={nodes.teddybear.geometry} material={materials.teddybear} position={[-0.68, 0.48, 0.49]} rotation={[-Math.PI, 0.32, -Math.PI]} scale={0.04} />
        <mesh name="Desk" geometry={nodes.Desk.geometry} material={materials.desk} position={[0.88, 0.42, 0.61]} rotation={[0, Math.PI / 2, 0]} scale={[0.0055, 0.05, 0.0055]} />
        <mesh name="nightstand" geometry={nodes.nightstand.geometry} material={materials.nightStand} position={[-0.1, 0.1, 0.84]} rotation={[0, Math.PI / 2, 0]} scale={[0.005, 0.05, 0.006]} />
        <mesh name="pillow" geometry={nodes.pillow.geometry} material={materials.lamp} position={[-0.59, 0.47, 0.76]} rotation={[-0.7, -1.57, 0]} scale={[0.13, 0.13, 0.2]} />
        <mesh name="rug" geometry={nodes.rug.geometry} material={materials.blackRug} position={[0.36, -0.01, -0.35]} rotation={[Math.PI, -1.49, Math.PI]} scale={0.48} />
        <mesh name="mouseKeyboard" geometry={nodes.mouseKeyboard.geometry} material={materials.keyboardMouse} position={[0.53, 0.27, 0.56]} rotation={[Math.PI / 2, -1.57, 0]} scale={[0.03, 0.04, 0.03]} />
        <mesh name="chicken" geometry={nodes.chicken.geometry} material={materials.chicken} position={[0.24, 0.38, 0.71]} rotation={[0, -0.35, 0]} scale={0.01} />
        <mesh name="lavaNeon001" geometry={nodes.lavaNeon001.geometry} material={materials.lavaLamp} position={[-0.85, 0.91, -0.43]} rotation={[0, Math.PI / 2, 0]} scale={[0.03, 0.01, 0.03]} />
        <mesh name="Icosphere001" geometry={nodes.Icosphere001.geometry} material={materials['Material.006']} position={[0.32, 0.35, -0.4]} rotation={[0, Math.PI / 2, 0]} scale={0.01} />
        <mesh name="chalk00" geometry={nodes.chalk00.geometry} material={materials.poolChalk} position={[0.47, 0.37, 0]} rotation={[0, 1.46, 0]} scale={[0.006, 0.006, 0.006]} />
        <mesh name="poolTableFinished" geometry={nodes.poolTableFinished.geometry} material={materials.poolTable} position={[0.36, 0.26, -0.36]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.04, 0.15, 0.02]} />
        <mesh name="poolCue00" geometry={nodes.poolCue00.geometry} material={materials.poolCue} position={[0.08, 0.43, -0.77]} rotation={[2.95, 0.44, -1.09]} scale={[0.33, 0, 0]} />
        <mesh name="Text" geometry={nodes.Text.geometry} material={materials.black} position={[0.04, 0.21, 1.08]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 2.6, 0.66]} />
        <mesh name="wallMount00004" geometry={nodes.wallMount00004.geometry} material={materials['Material.008']} position={[0.4, 1.4, -0.37]} scale={[0.03, 0.11, 0.01]} /> */}